### ISSUE TITLE
Fix background wallpaper 

### ISSUE THREAD

**Issue by Mnguyener** [Brod8362/csoc4353#30]
The website's wallpaper does not tile properly. It needs to be more seamless when readjusting the dimensions of the page and in scrolling.

**Comment by Brod8362** [comment]
Ideally, the background is made up of two layers:
- A lower sand layer which tiles horizontally
- The star backdrop which tiles horizontally & vertically seamlessly

Not sure how to pull that off but I'm sure its possible

**Comment by bbqcandy** [comment]
A simple suggestion for the sky background:
Instead of having one large image for the sky or a tiling background, we could just have a solid color, and place various star sprites (possibly animated) over that background.

**Comment by Mnguyener** [comment]
I like the idea of having star sprites. I'll get to working on that after Friday!

**Comment by Mnguyener** [comment]
In my recent PR, I've done the two background layers. All that needs to be changed is the actual image
