### ISSUE TITLE
Indicate input fields are required

### ISSUE THREAD

**Issue by Mnguyener** [Brod8362/csoc4353#32]
Here's  a helpful [link](https://stackoverflow.com/questions/11197671/use-css-to-automatically-add-required-field-asterisk-to-form-inputs)

**Comment by Brod8362** [comment]
Most browsers have a feature for this if the form is configured properly

**Comment by Mnguyener** [comment]
True, technically we don't need to do this because if the user doesn't submit all required info, the form will point it out.
