### ISSUE TITLE
Fuel Quote Form does not need to select address

### ISSUE THREAD

**Issue by bbqcandy** [Brod8362/csoc4353#39]
Address 1 and 2 are a part of the same address and not separate addresses (sorry that's my mistake), therefore users don't actually have to select their address when filling out the fuel quote form, it should be automatically filled in from the database. That said though, it would be nice if the users could see their address from the db when submitting the form, but that may not be necessary.

**Comment by Mnguyener** [comment]
Pending resolution by #50
