### ISSUE TITLE
Considerations for a new layout?

### ISSUE THREAD

**Issue by Brod8362** [Brod8362/csoc4353#43]
Our site at its core has basically two functions - so I'm wondering if another layout might be ideal
(I'm not really sure what that layout would look like, I'm open to ideas)

**Comment by Mnguyener** [comment]
What do you mean by layout? Like simplify the page structure even more?

**Comment by Brod8362** [comment]
![image](https://github.com/Brod8362/csoc4353/assets/38388134/88c93a01-ae66-4a26-a436-99f28bf3d253)

This is not to scale, its just a visual for what I have in mind

**Comment by bbqcandy** [comment]
I feel like to simplify further, the landing page could just be the the fuel quote page with a button to generate a new quote, view & edit profile, and logout.

![Screenshot from 2024-04-09 11-56-15](https://github.com/Brod8362/csoc4353/assets/114030730/c053580d-7421-48f2-8c1b-510894ec3b9d)

**Comment by Brod8362** [comment]
I'm fine w/ this personally
