### ISSUE TITLE
Icon designs needed

### ISSUE THREAD

**Issue by bbqcandy** [Brod8362/csoc4353#52]
Here is a list of the alt names needed for icons in each page:

* Fuel quote form:
   * "fuel icon" (`gallons_requested`)
   * "house icon" (`address1` and `address2`)
   * "calendar icon" (`delivery_date`) *any suggestions on what this should look like?*
   * "money icon" (price-per-gallon and total amount due) *should these share an icon, should we remove the icon from one of them?*
   * "checkmark icon (submit form)
* Fuel quote page:
   * most of these are the same as above excpet for:
   * "truck icon" (delivery_date) *this page also has a separate `current date`which uses the "calendar icon" from above, maybe these should just be the same?*
* Login page:
   * "person icon" (`username`)
   * "key icon" ('password`)
   * "arrow icon" (`login`) *it might be best to replace this one with another checkmark icon like what we do for other submits*
   * "pencil icon" (`register`)
* Profile management page:
   * *most of the icons in this page are covered above*
   * "city icon" (`city`)
   * "state icon" ('state')
   * "zip code icon" ('zip')
   * *the three icons above would not only be difficult to design, but they might also be entirely unnecessary, as long as we format in a way such that these could be displayed with the house icon for addresses instead.

I can start designing some of them, but we should also try and reformat the pages so unnecessary icons are removed.

**Comment by Brod8362** [comment]
Closed by #63
