### ISSUE TITLE
Change the Quote IDs displayed to be incremental and not show the actual ID

### ISSUE THREAD

**Issue by tnttruong** [Brod8362/csoc4353#62]
![image](https://github.com/Brod8362/csoc4353/assets/33504642/b7322c26-ef4a-426c-a2b3-4ded0a6ff2b5)

These should be incremental and display `Quote 1`, `Quote 2` for example rather than a hashed ID

**Comment by Brod8362** [comment]
Instead of this, why don't we show the delivery date and total price of the quote? This avoids having to create any new data

**Comment by Brod8362** [comment]
e.g, `Quote for 4/21/24 ($1000)`

**Comment by tnttruong** [comment]
This sound a lot easier to implement that what I'm trying to do, thanks for the tip

**Comment by Brod8362** [comment]
Closed be #85
